#render.yaml (en la raiz de tu repo)

services:
  # Backend
  - type: web
    name: paserBackend
    env: node
    branch: master
    rootDir: backend-mongodb
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: PORT
        value: "5000"
      - key: MONGOODB-URI
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_APP_PASS
        sync: false
      - key: FRONTEND_URL
        value: https://paserFrontend.onrender.com
